### ISSUE TITLE
org-mode support?

### ISSUE THREAD

**Issue by fkgruber** [chep/copilot-chat.el#10]
Thanks for bringing copilot chat support to emacs. Seems like org-mode support would be really useful. Any plans?

**Comment by chep** [comment]
What do you mean by org-mode support ?
I don't use org-mode but if you can tell me more, I can have a look.

**Comment by fkgruber** [comment]
You can see some of the features here:
https://orgmode.org/features.html

But basically instead of putting the results on a text buffer you could use orgmode format. This way you add headings, source code in any language, etc. Afterwards the user can execute code  get results and so on.

**Comment by chep** [comment]
Please try org-mode branch and tell me what you need.

**Comment by chep** [comment]
I created a new branch named `frontend` and will continue on it. You can set `copilot-chat-frontend` to `'org` to have the same behavior of org-mode branch.
I have trouble with the prompt to make copilot use org syntax. Despite my prompt telling explicitly to use this syntax and not markdown, it sometimes still use markdown...
I found a tool named pandoc to convert markdown to org but it would be better not to depend on an external program.
If you have any idea, tell me.

**Comment by fkgruber** [comment]
I tried the orgmode branch and seems to work. However I noticed when I asked to generate some elisp code I got:
** *[08:56:19]* Sure, to print text in Emacs Lisp (elisp), you can use the `message` function. Here's an example:

#+BEGIN_SRCisp
(message "Hi")
#+END_SRC

When you evaluate this code,Hi" will be printed in the echo (the line at the bottom of the Emacs window).

instead of #+BEGIN_SRC elisp

**Comment by fkgruber** [comment]
also it would be useful to have an option where the output is written on an existing file. For example, I may have an opened org file then I could call a function that would let me make a query and write the results to the same file

**Comment by chep** [comment]
> I tried the orgmode branch and seems to work. However I noticed when I asked to generate some elisp code I got: ** _[08:56:19]_ Sure, to print text in Emacs Lisp (elisp), you can use the `message` function. Here's an example:
> 
> #+BEGIN_SRCisp (message "Hi") #+END_SRC
> 
> When you evaluate this code,Hi" will be printed in the echo (the line at the bottom of the Emacs window).
> 
> instead of #+BEGIN_SRC elisp

You are missing some data "emacs-l" token has been lost. I had the problem in the past. Try the `frontends` branch, this should be resolved.

**Comment by chep** [comment]
Hi,

I added `copilot-chat-ask-and-insert`. It should do what you wanted.

**Comment by fkgruber** [comment]
Hi Chep,
I set the frontend to org but when I use copilot-chat-ask-and-insert it still generates markdown code.

**Comment by chep** [comment]
> Hi Chep, I set the frontend to org but when I use copilot-chat-ask-and-insert it still generates markdown code.

Sometimes it does this to me. I explicitly tell copilot to use org-mode syntax several times in the prompt but sometimes, it just ignores it and generate markdown… You can try to modify `copilot-chat-prompt`, I don't have any better solution.

Here is the part of the prompt about org :
```
Use only Emacs org-mode formatting in your answers\nMake sure to include the programming language name at the start of the org-mode code blocks.\nThis is an example of python code block in emacs org-mode syntax:\n#+BEGIN_SRC python\ndef hello_world():\n	print('Hello, World!')\n#+END_SRC\nAvoid wrapping the whole response in the block code.\n\nDon't forget the most important rule when you are formatting your response: use emacs org-mode syntax only.
```
