### ISSUE TITLE
copilot-chat getd one-time code again and again

### ISSUE THREAD

**Issue by parsifal9** [chep/copilot-chat.el#18]
Hi Chep,

I am having a problem getting copilot-chat working.
1) i have copilot.el working 
2) I cloned your repository
3) I have added this to my .emacs file
```
(add-to-list 'load-path "/home/user/local/share/elisp/copilot-chat.el")
(require 'copilot-chat)
(setq copilot-chat-frontend  'markdown) 

```
It seems to load with no problem but every time I try to use it I get a message like
```
Your one-time code EEEE-EEEE is copied. Press ENTER to open GitHub in your browser. If your browser does not open automatically, browse to https://github.com/login/device.
```
even If I register the device again -- it still does not work.
Am I doing something wrong?

Bye

**Comment by chep** [comment]
Hi,

I can't reproduce the bug. 

- I started `emacs -Q` 
- I evaluated 
``` elisp
(add-to-list 'load-path "/home/chep/.emacs.d/straight/repos/emacs-request")
(add-to-list 'load-path "/home/chep/.emacs.d/straight/repos/markdown-mode")
(add-to-list 'load-path "/home/chep/outils/copilot-chat.el")
(require 'copilot-chat)
(setq copilot-chat-frontend  'markdown)
```
- I Removed `~/.cache/copilot-chat/token` and `~/.config/copilot-chat/github-token `
- I started to chat and authentication just worked fine.

Can you check your `~/.cache/copilot-chat/token` and `~/.config/copilot-chat/github-token ` files ?

**Comment by parsifal9** [comment]
Thanks chep,
1) I was just cloning the repository and evaluating files in emacs i.e. not using straight
2) 
~/.cache/copilot-chat/token  -- does not exist 
~/.config/copilot-chat/    is empty

3) do I need to use straight? I have started installing it but it is more than a little daunting.
Bye

**Comment by chep** [comment]
You don't need to use straight but copilot-chat needs markdown-mode and emacs-requests.
I just load them manually. As I'm using straight, their files are in my straight directory but here, I'm not using it. 
I think you load them somewhere in your config because without them you cannot evaluate copilot-chat code. 

Do you have something related to copilot-chat in messages, warnings or errors buffers?

**Comment by parsifal9** [comment]
Hi Chep,
It all works now. I loaded temp.el (see below) and it gave me a github key and
there is now a file in ``` ~/.config/copilot-chat/github-token```

```
(add-to-list 'load-path "/home/user/.emacs.d/elpa/request-20230127.417")
(add-to-list 'load-path "/home/user/.emacs.d/elpa/markdown-mode-20220603.300")
(add-to-list 'load-path "/home/user/local/share/elisp/copilot-chat.el")
(require 'markdown-mode)
(require 'request)
(require 'copilot-chat)
(setq copilot-chat-frontend  'markdown)
```

Unfortunately I don't know what the problem was. There are no error messages,
and it just worked. Could the "require" lines have made a difference?
I will close this job. Thanks for your help.

Bye

**Comment by chep** [comment]
Happy to see you fixed it.
When possible I'll make a pull request to add the package in melpa.
