### ISSUE TITLE
use question (possibly simple)

### ISSUE THREAD

**Issue by parsifal9** [chep/copilot-chat.el#19]
Hi Chep,
I have a very simple use question.
When I start copilot-chat-mode it turns the buffer I an working in into "read only".
After I have asked some chat questions about the code, I would like to go back to editing the buffer,
so I assume that I need to turn  copilot-chat-mode off in that buffer?
I have tried
```
M-x copilot-chat-list-add-or-remove-buffer 
```
which gives me a list of buffers including the one I am working on. However, I can't see what to do with the list, which is also read-only.

**Comment by chep** [comment]
Hi,

Copilot-chat-mode is used (internaly) in *copilot-chat* buffer. You should not use it. Use `copilot-chat-display` to open copilot-chat buffers and start chatting.

I need to improve the readme.

**Comment by parsifal9** [comment]
I see now. Totally different user experience!  Thanks
