### ISSUE TITLE
Pressing <prior> during answer generation in a copilot-chat-shell buffer deletes the buffer contents

### ISSUE THREAD

**Issue by dov** [chep/copilot-chat.el#23]
# To reproduce

1. Run `copilot-chat-shell-maker-display`
2. Enter a prompt generating a non-trivial response, e.g.: "If a class `loader` populates a class `scene`, what's the pattern name of `loader`?"
3. After a second or two in the middle of Github Copilots generation of the answer, press the PageUp key.

# The result

All the contents in the buffer prior to pressing PageUp key is lost. Undo doesn't help, and I haven't found a way to retrieve the lost contents.

# Expected result

The buffer should scroll, but its contents should not be affected.

**Comment by chep** [comment]
I can reproduce it with any key.

**Comment by chep** [comment]
I think this is a "bug" in shell maker. It may not be designed to receive data from background callbacks. In normal use, input is not managed until callback is finished. But in copilot-chat, callback do finish and then background process sends data when it arrives.

I can wait data in callback and fix the bug but emacs will freeze during data reception.

I will ask shell-maker author to help me.

**Comment by dov** [comment]
Thanks. Indeed any key causes the problem. Apparently the previous text isn't deleted, but there is a new buffer created at the time of the keypress.

Would it be possible to inhibit the response to any key presses, while the background process sends data?

**Comment by chep** [comment]
Actually it seems that polymode is the problem.
Work in progress…

**Comment by chep** [comment]
I removed polymode and used a temp buffer for markdown management. It seems to work. Tell me if I can close the issue.

**Comment by dov** [comment]
Looks great! It's working much better now. Thanks! I'm closing the issue.
