### ISSUE TITLE
Surprised C-c C-c doesn't submit

### ISSUE THREAD

**Issue by skybert** [chep/copilot-chat.el#36]
In my experience, `C-c C-c`, is the normal "submit" shortcut. With `copilot-chat`, this is `C-c RET`, is there any good reason for this deviation?

Thanks for creating `copilot-chat`, it's a useful mode for us wanting to live inside of Emacs :smile:

**Comment by chep** [comment]
You're right, I'm gonna add `C-c C-c`.

**Comment by skybert** [comment]
Excellent!
