### ISSUE TITLE
"Wrong number of arguments" after updating Emacs packages

### ISSUE THREAD

**Issue by mikaelspringer** [chep/copilot-chat.el#37]
I made an update of all my Emacs packages today, after this copliot-chat does not work. Doing `M-x copilot-chat-display` brings up the copilot chat window, when I enter anything to chat with copilot I get the following error;

`shell-maker--eval-input-on-buffer-v2: Wrong number of arguments: #<subr copilot-chat--shell-cb>, 2`

copilot-chat version is 20241102.1936, shell-maker version is 20241102.850 (according to describe-package), Emacs version is 30.0.92 (emacs-plus@30 through homebrew on macOS).

**Comment by matoi** [comment]
I’ve been experiencing the same issue since a few days ago.

For now, to make copilot-chat work, forcing the callback function of copilot-chat to be called in the v1 way from shell-maker should be sufficient. While this is not a fundamental solution, it can be achieved temporarily by replacing the shell-maker function.

```emacs-lisp
(with-eval-after-load 'copilot-chat-shell-maker

  (add-hook 'copilot-chat-shell-mode-hook
    (lambda ()
      (setq-local shell-maker-use-eval-input-on-buffer-v1 t)))

  (cl-defun shell-maker-submit (&key input on-output on-finished)
    "Submit current input.

Optionally, insert INPUT into shell.

If invoked programmatically, get notified:

Use ON-OUTPUT: function to monitor command response text.

Of the form:

 (lambda (response)
  (message \"Command: %s\" response))

Use ON-FINISHED: function to monitor when command is finished.

Of the form:

 (lambda (input output success)
  (message \"Finished: %s\" success))."
    (interactive)
    (unless (eq major-mode (shell-maker-major-mode shell-maker--config))
      (user-error "Not in a shell"))
    (let* ((shell-buffer (shell-maker-buffer shell-maker--config))
            (called-interactively (called-interactively-p #'interactive))
            (command-handler (shell-maker-config-execute-command shell-maker--config))
            ;;
            (is-command-v1 (or shell-maker-use-eval-input-on-buffer-v1
                             (and (closurep command-handler)
                               (string-match-p "shell-maker-async-shell-command"
                                 (format "%s" command-handler)))))
            (shell-maker--input))
      (when input
        (with-current-buffer shell-buffer
          (goto-char (point-max))
          (insert input)))
      (comint-send-input) ;; Sets shell-maker--input
      (when (shell-maker--clear-input-for-execution shell-maker--input)
        (if called-interactively
          (if is-command-v1
            (shell-maker--eval-input-on-buffer-v1 :input shell-maker--input
              :config shell-maker--config)
            (shell-maker--eval-input-on-buffer-v2 :input shell-maker--input
              :config shell-maker--config))
          (if is-command-v1
            (shell-maker--eval-input-on-buffer-v1 :input shell-maker--input
              :config shell-maker--config)
            (shell-maker--eval-input-on-buffer-v2 :input shell-maker--input
              :config shell-maker--config
              :on-output-broadcast on-output
              :on-finished-broadcast on-finished)))))))
```

Here is the part of the function where the modifications were made:

```emacs-lisp
(is-command-v1 (or shell-maker-use-eval-input-on-buffer-v1
                             (and (closurep command-handler)
                               (string-match-p "shell-maker-async-shell-command"
                                 (format "%s" command-handler)))))
```

Please note, however, that since the entire function is being replaced, this setup will likely need to be updated whenever shell-maker is updated.

It seems that if the copilot-chat callback function were to support the v2 method of invocation by shell-maker, it would solve the issue, but I haven’t investigated that far.

**Comment by chep** [comment]
I can't reproduce the problem. 

BUT, I changed some code to clean it and make it easier to add new features. shell-maker is now a regular backend and does not need specific configuration anymore.

Here is my configuration :
```
(use-package copilot-chat
  :straight (:host github :repo "chep/copilot-chat.el" :files ("*.el"))
  :after (request shell-maker)
  :custom
  (copilot-chat-frontend 'shell-maker))
```

Anyway, I can't reproduce the bug even with old config.
I'm gonna work on it.

**Comment by chep** [comment]
Ok, I double checked my shell-maker version and in fact, it was not up to date (pull failed because of local changes). That's why it worked for me.

**Comment by chep** [comment]
Please try `shell-maker-update` branch. I made a quick fix but did not test enough.

**Comment by mikaelspringer** [comment]
The `shell-maker-update` branch works for me. I haven't done extensive testing, though, but it looks promising.

**Comment by isentropic** [comment]
Confirm it works, thank a lot
