### ISSUE TITLE
Enable Claude for copilot chat

### ISSUE THREAD

**Issue by bluzky** [chep/copilot-chat.el#39]
Hi, I saw this announcement from Github few days ago

https://docs.github.com/en/copilot/using-github-copilot/using-claude-sonnet-in-github-copilot 

It would be awesome if there is option to enable claude sonnet 3.5 model

Thanks

**Comment by chep** [comment]
Have you tried to change `copilot-chat-model`?

**Comment by bluzky** [comment]
Thanks, it works. There is no document for this custom.
` (copilot-chat-model "claude-3.5-sonnet")`

**Comment by chep** [comment]
Good.
I'll document customizable variables in readme.
