### ISSUE TITLE
Add option to not follow copilot-chat--shell-cb-prompt point?

### ISSUE THREAD

**Issue by kwrooijen** [chep/copilot-chat.el#47]
When asking a question to Copilot Chat using shell-maker, the current point continuously jumps to the end of the chat buffer. This is because the current point is being modified without the use of `save-excursion`.

https://github.com/chep/copilot-chat.el/blob/d2f3ef17d755d8920c747ee5677db5b003a13406/copilot-chat-shell-maker.el#L105-L129

This might be intended behavior, but I find it very challenging to read Copilot's responses until the message is finalized.

Suggested options:

1. If this is intended behavior, add an option to wrap the entire body of `copilot-chat--shell-cb-prompt` in a `save-excursion` block.
2. If this is intended behavior, wrap the body in `save-excursion` and add an option to scroll down after an input. At the end of `copilot-chat--shell-cb-prompt` add `(when option (goto-char (point-max))` (outside of save-excursion).
3. If this is not intended behavior, simply wrap the body in `save-excursion` without an option to disable it.

**Comment by chep** [comment]
Can you test the new branch 47-shell-follow ?
There will be a new custom `copilot-chat-shell-maker-follow`. You should set it to nil.

**Comment by kwrooijen** [comment]
```emacs-lisp
(defun copilot-chat--shell-cb-prompt-wrapper (shell content)
  (if copilot-chat-shell-maker-follow
    (copilot-chat--shell-cb-prompt)
    (save-excursion
      (copilot-chat--shell-cb-prompt))))
;;...
(apply-partially #'copilot-chat--shell-cb-prompt-wrapper shell)
```

I believe something like this would fix it

**Comment by chep** [comment]
I already tried something like this in the past. I got problems with shell-maker.

**Comment by kwrooijen** [comment]
FWIW this is how I currently resolve the issue locally. By redefining `copilot-chat--shell-cb-prompt`

```emacs-lisp
(defun copilot-chat--shell-cb-prompt (shell content)
   "Callback for Copilot Chat shell-maker.
 Argument CALLBACK is the callback function to call.
 Argument ERROR-CALLBACK is the error callback function to call.
 Argument CONTENT is copilot chat answer."
   (save-excursion
     (with-current-buffer copilot-chat--buffer
       (goto-char (point-max))
       (when copilot-chat--first-word-answer
         (setq copilot-chat--first-word-answer nil)
         (let ((str (format-time-string "# [%T] Copilot:\n"))
               (inhibit-read-only t))
           (with-current-buffer copilot-chat--shell-maker-temp-buffer
             (insert str))
           (funcall (map-elt shell :write-output) str)))
       (if (string= content copilot-chat--magic)
           (progn
             (funcall (map-elt shell :finish-output) t) ; the end
             (copilot-chat--shell-maker-copy-faces)
             (setq copilot-chat--first-word-answer t))
         (progn
           (with-current-buffer copilot-chat--shell-maker-temp-buffer
             (goto-char (point-max))
             (let ((inhibit-read-only t))
               (insert content)))
           (funcall (map-elt shell :write-output) content))))))
```

**Comment by chep** [comment]
> ```emacs-lisp
> (defun copilot-chat--shell-cb-prompt-wrapper (shell content)
>   (if copilot-chat-shell-maker-follow
>     (copilot-chat--shell-cb-prompt)
>     (save-excursion
>       (copilot-chat--shell-cb-prompt))))
> ;;...
> (apply-partially #'copilot-chat--shell-cb-prompt-wrapper shell)
> ```
> 
> I believe something like this would fix it, and then you won't have to change any of the logical code.

You're right, it seems to work. I pushed your code and added the `copilot-chat-shell-maker-follow` custom (default is t).

**Comment by chep** [comment]
Tell me if I can close the issue.
