### ISSUE TITLE
define fonts for copilot-chat-list

### ISSUE THREAD

**Issue by cehteh** [chep/copilot-chat.el#54]
In my theme the fonts for default/keyword are pretty similar. It would be nice if you could define dedicated fonts for whats included/excluded.

**Comment by chep** [comment]
I pushed a new commit.

You can customize the appearance of the buffer list by modifying these faces:
- `copilot-chat-list-default-face` - Face used for unselected buffers in the buffer list.
- `copilot-chat-list-selected-buffer-face` - Face used for selected buffers in the buffer list.
