### ISSUE TITLE
The '_' character has been removed in the copilot-chat text.

### ISSUE THREAD

**Issue by t-kudou** [chep/copilot-chat.el#55]
In the copilot-chat result text, the '_' character is missing from function names, variable names, etc. If the same query is performed in vscode, the result will contain the _ character.

**Comment by chep** [comment]
Could you give me a prompt that would reproduce the problem? I have no problem with '_' and there is no code that could remove it (as far as I know).

**Comment by t-kudou** [comment]
The reported problem occurred, for example, at the following prompts
"Could you show me, how to convert from sqlalchemy query output to pandas DataFrame?"
However, when I ran it again today, it returned results with the correct '_'.

**Comment by chep** [comment]
OK. Tell me if it happens again.
