### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by S2Ler** [chep/copilot-chat.el#6]

**Comment by chep** [comment]
Hi,

I need more details…

**Comment by chep** [comment]
There is `url-proxy-services` variable in the url lib, can you try it ? I hope it will work without modification in copilot-chat.
```elisp
(setq url-proxy-services
   '(("no_proxy" . "^\\(localhost\\|10.*\\)")
     ("http" . "proxy.com:8080")
     ("https" . "proxy.com:8080")))
```

**Comment by S2Ler** [comment]
```
(setq url-proxy-services
   '(("no_proxy" . "^\\(localhost\\|10.*\\)")
     ("http" . "proxy.com:8080")
     ("https" . "proxy.com:8080")))
```

won't it set proxy globally for emacs? I want to proxy only requests to GitHub copilot through proxy.

Similar to how https://github.com/copilot-emacs/copilot.el#copilot-network-proxy does it.

**Comment by chep** [comment]
Ok, I'm gonna have a look.

**Comment by getong** [comment]
Great work, need this feature.

**Comment by getong** [comment]
My config:
```
(use-package shell-maker
  :straight (:host github :repo "xenodium/chatgpt-shell" :files ("shell-maker.el")))

(use-package chatgpt-shell
  :requires shell-maker
  :straight (:host github :repo "xenodium/chatgpt-shell" :files ("chatgpt-shell.el")))

(use-package copilot-chat
  :straight (:host github :repo "chep/copilot-chat.el" :files ("*.el"))
  :after (request shell-maker)
  :custom
  (copilot-chat-frontend 'shell-maker)
  :config
  (require 'copilot-chat-shell-maker)
  (push '(shell-maker . copilot-chat-shell-maker-init) copilot-chat-frontend-list)
  (copilot-chat-shell-maker-init))

(use-package polymode
  :straight t
  :config
  (add-to-list 'auto-mode-alist '("\\.Rmd" . poly-markdown+r-mode)))
```
I close emacs and reopen it, and I need to register and setup my github device every time.
I think this might be the network problem.
Is it possible to store my authority key in some text file in my local storage?

**Comment by chep** [comment]
> I close emacs and reopen it, and I need to register and setup my github device every time. I think this might be the network problem. Is it possible to store my authority key in some text file in my local storage?

github token is in `~/.config/copilot-chat`. This is the token obtained when you are doing the github registation.
Then, this token is used to create a session and a new token is stored in `~/.cache/copilot-chat`. This token as an expiration date but can be renewed without manual authentication.

I think you have a problem with `~/.config/copilot-chat/github-token` can you check if this file exists before starting emacs / copilot-chat ?

**Comment by chep** [comment]
Anyway this should be a separated issue.

Proxy is next issue I'll work on.

**Comment by getong** [comment]
> > I close emacs and reopen it, and I need to register and setup my github device every time. I think this might be the network problem. Is it possible to store my authority key in some text file in my local storage?
> 
> github token is in `~/.config/copilot-chat`. This is the token obtained when you are doing the github registation. Then, this token is used to create a session and a new token is stored in `~/.cache/copilot-chat`. This token as an expiration date but can be renewed without manual authentication.
> 
> I think you have a problem with `~/.config/copilot-chat/github-token` can you check if this file exists before starting emacs / copilot-chat ?

I do have this file in this directory, and it does contain my github token.

**Comment by getong** [comment]
I use `copilot-chat-ask-and-insert` everytime.
Does it matter?

**Comment by chep** [comment]
It should not but…
Can you try `copilot-chat-display` ?

**Comment by getong** [comment]
By using `copilot-chat-display`, it works fine.
It must be the `copilot-chat-ask-and-insert` problem.

**Comment by chep** [comment]
> By using `copilot-chat-display`, it works fine. It must be the `copilot-chat-ask-and-insert` problem.

Please try the `insert` branch: https://github.com/chep/copilot-chat.el/tree/insert and tell me if it is fixed.

**Comment by getong** [comment]
> > By using `copilot-chat-display`, it works fine. It must be the `copilot-chat-ask-and-insert` problem.
> 
> Please try the `insert` branch: https://github.com/chep/copilot-chat.el/tree/insert and tell me if it is fixed.

It works, thanks.

**Comment by chep** [comment]
Backends are now in separated file to make the code cleaner. Now I "just" have to implement proxy for each one of them.

**Comment by chep** [comment]
… I know nothing about proxies.

It seems to be easy for http and socks proxy. But for https, there are a lot of options in curl :

```
 proxy-cacert
    Use the specified certificate file to verify the HTTPS proxy. The file may contain multiple CA certificates. The certificate(s) must be in PEM format.

proxy-cert
    Use the specified client certificate file when communicating with an HTTPS proxy. The certificate must be in PKCS#12 format if using Secure Transport, or PEM format if using any other engine. If the optional password is not specified, it is queried for on the terminal. Use --proxy-key to provide the private key.

proxy-cert-type
   Set type of the provided client certificate when using HTTPS proxy. PEM, DER, ENG and P12 are recognized types.

proxy-ciphers <list>
     Same as --ciphers but used in HTTPS proxy context.

     Specifies which ciphers to use in the connection to the HTTPS proxy. The list of ciphers must specify valid ciphers. Read up on SSL cipher list details on this URL:

proxy-crlfile <file>
     Provide filename for a PEM formatted file with a Certificate Revocation List that specifies peer certificates that are considered revoked when communicating with an HTTPS proxy.

proxy-key <key>
     Specify the filename for your private key when using client certificates with your HTTPS proxy. This option is the equivalent to --key but used in HTTPS proxy context.

proxy-key-type <type>
     Specify the private key file type your --proxy-key provided private key uses.  DER, PEM, and ENG are supported. If not specified, PEM is assumed.

proxy-pass <phrase>
     Passphrase for the private key for HTTPS proxy client certificate.

proxy-tlsauthtype <type>
     Set TLS authentication type with HTTPS proxy. The only supported option is "SRP", for TLS-SRP (RFC 5054). This option works only if the underlying libcurl is built with TLS-SRP support.

proxy-tlspassword <string>
     Set password to use with the TLS authentication method specified with --proxy-tlsauthtype when using HTTPS proxy. Requires that --proxy-tlsuser is set.

proxy-tlsuser <name>
     Set username for use for HTTPS proxy with the TLS authentication method specified with --proxy-tlsauthtype. Requires that --proxy-tlspassword also is set.

proxy-user <user:password>
     Specify the username and password to use for proxy authentication.
```
Do you see useless or missing options in that list ?

**Comment by S2Ler** [comment]
I would be happy with simple http proxy if you ask me.

**Comment by getong** [comment]
I have test the code, it works well.
my config:
```
(use-package copilot-chat
  :straight (:host github :repo "chep/copilot-chat.el" :branch "proxy" :files ("*.el"))
  :after (request shell-maker)
  :custom
  (copilot-chat-frontend 'shell-maker)
  (copilot-chat-frontend 'org)
  (copilot-chat-curl-proxy "socks5://localhost:7897")
  :config
  (require 'copilot-chat-shell-maker)
  (push '(shell-maker . copilot-chat-shell-maker-init) copilot-chat-frontend-list)
  (copilot-chat-shell-maker-init))
```

**Comment by S2Ler** [comment]
Also confirming it works for me, thank you!
